//Every time I have to refresh these tokens because they will be exparied after a period of time. To get new one I need to go to auth.rest and generate new tokens.

@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2OTY2YzBiNGVkOGU1ZmM0N2E3MTNjZTciLCJpc0FkbWluIjp0cnVlLCJpYXQiOjE3NjgzNDQwNzEsImV4cCI6MTc2ODM0NzY3MX0.YiHiWZOzNZLlvzxH6WfTTCBJ8b4igoJaeUgaSPma4Ro

GET http://localhost:3001/api/agents?pageNumber=1&pageSize=10&name=H
x-auth-token: {{token}}

###

GET http://localhost:3001/api/agents/allAgents
x-auth-token: {{token}}

###

GET http://localhost:3001/api/agents/6966d4944add0fe0fdfa1a96
x-auth-token: {{token}}

###

POST http://localhost:3001/api/agents
x-auth-token: {{token}}
Content-Type: application/json


{
    "name": "Harun",
    "email": "Harun@gmail.com",
    "phone": "019232442113",
    "whatsappNumber": "019232442113",
    "region": "Dhaka",
    "city": "Munshiganj - Town",
    "area": "Munshiganj Sadar Mirkadim",
    "location": "Road 2/20"
}

###

PUT http://localhost:3001/api/agents/6966d4944add0fe0fdfa1a96
x-auth-token: {{token}}
Content-Type: application/json


{
    "name": "Harun",
    "email": "Harun@gmail.com",
    "phone": "019232442114",
    "whatsappNumber": "019232442113",
    "region": "Dhaka",
    "city": "Munshiganj - Town",
    "area": "Munshiganj Sadar Mirkadim",
    "location": "Road 2/20"
}

###

DELETE http://localhost:3001/api/agents/6966d4944add0fe0fdfa1a96
x-auth-token: {{token}}
Content-Type: application/json