@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2OTZkMmVkYWMyNjdiMzQ5Mzk0ZGFkMjMiLCJpc0FkbWluIjp0cnVlLCJpYXQiOjE3Njg4NjAzNjcsImV4cCI6MTc2ODg2Mzk2N30.lx2M6deAMXoMyMcrt1mIVYrGpaCZBRq1NHTcrK8H7zc
@refresh_token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2OTY2YzBiNGVkOGU1ZmM0N2E3MTNjZTciLCJpc0FkbWluIjp0cnVlLCJpYXQiOjE3NjgzNDQwNzEsImV4cCI6MTc2ODM2NTY3MX0.4PKYRryrO61OvjLBxk3By8Ke7D-fAgQdn24N8LkolaM

###

POST http://localhost:3001/api/auth/
Content-Type: application/json

{
    "email": "rhymecanada665@gmail.com",
    "password": "123456"
}

###

POST http://localhost:3001/api/auth/newToken
refresh-token: {{refresh_token}}



###

POST http://localhost:3001/api/auth/forgot-password
Content-Type: application/json

{
    "email": "rhymemorshed665@gmail.com"
}


###

GET http://localhost:3001/api/auth/google