//Every time I have to refresh these tokens because they will be exparied after a period of time. To get new one I need to go to auth.rest and generate new tokens.
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2OTZkMmVkYWMyNjdiMzQ5Mzk0ZGFkMjMiLCJpc0FkbWluIjp0cnVlLCJpYXQiOjE3Njg4NjAzNjcsImV4cCI6MTc2ODg2Mzk2N30.lx2M6deAMXoMyMcrt1mIVYrGpaCZBRq1NHTcrK8H7zc


GET http://localhost:3001/api/orders?pageNumber=1&pageSize=10
x-auth-token: {{token}}

###

GET http://localhost:3001/api/orders/totalProfit
x-auth-token: {{token}}

###

GET http://localhost:3001/api/orders/sellsInMonth
x-auth-token: {{token}}

###

GET http://localhost:3001/api/orders/countOrderCategory
x-auth-token: {{token}}

###

GET http://localhost:3001/api/orders/pendingOrder
x-auth-token: {{token}}

###

GET http://localhost:3001/api/orders/weeklySells
x-auth-token: {{token}}

###

GET http://localhost:3001/api/orders/6966f1813ba5a71ff2f60913
x-auth-token: {{token}}

###

POST http://localhost:3001/api/orders
x-auth-token: {{token}}
Content-Type: application/json

{
    "name": "Rhyme",
    "phone": "01944501581",
    "address": "Road 2/3, Gazaria Char Decree, Munshiganj - Gajaria, Dhaka",
    "arrivalDate": "7/31/2022, 1:06:35 PM",
    "arrivalTime": "7/31/2022, 1:06:35 PM",
    "category": "Repairing",
    "categoryType": "fan",
    "brand": "Walton",
    "model": "Demo",
    "problem": "Water Dropping",
    "note": "Urgent",
    "statusDetails": "Your order is pending",
    "statusState": "Pending"
}

###

PATCH http://localhost:3001/api/orders/accept/696ea2b74b7ad54462f4002d
x-auth-token: {{token}}
Content-Type: application/json

{
    "note": "Urgent2",
    "statusDetails": "Your order is Accepted",
    "statusState": "Accepted"
}

###

PATCH http://localhost:3001/api/orders/assigned/696ea2b74b7ad54462f4002d
x-auth-token: {{token}}
Content-Type: application/json

{
    "technicianId": "6966dc6348b2cc1ca29625d6",
    "statusDetails": "Technician Assigned has been assigned to your order",
    "statusState": "Technician Assigned"
}

###

PATCH http://localhost:3001/api/orders/repaired/696ea2b74b7ad54462f4002d
x-auth-token: {{token}}
Content-Type: application/json

{
    "amount": 100,
    "statusDetails": "Your product has been repaired. Please pay the bills",
    "statusState": "Product Repaired"
}