//Every time I have to refresh these tokens because they will be exparied after a period of time. To get new one I need to go to auth.rest and generate new tokens.
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2OTY2YzBiNGVkOGU1ZmM0N2E3MTNjZTciLCJpc0FkbWluIjp0cnVlLCJpYXQiOjE3NjgzNTY5NjQsImV4cCI6MTc2ODM2MDU2NH0.HNHy0qu3JNV2zm8qza_O2wlRsEiCkb-CQCqViBTQw_s


###

GET http://localhost:3001/api/payments/6966ee3685f27867c023f650
x-auth-token: {{token}}

###

POST http://localhost:3001/api/payments/paymentCancel
x-auth-token: {{token}}

###

POST http://localhost:3001/api/payments/paymentFail
x-auth-token: {{token}}