//Every time I have to refresh these tokens because they will be exparied after a period of time. To get new one I need to go to auth.rest and generate new tokens.
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2OTY2YzBiNGVkOGU1ZmM0N2E3MTNjZTciLCJpc0FkbWluIjp0cnVlLCJpYXQiOjE3NjgzNDgwNDksImV4cCI6MTc2ODM1MTY0OX0.hq8lwStrKpGfRsya6c8gPtr5soZ3DcwwMM1WjIfOOmU

###

POST http://localhost:3001/api/products
x-auth-token: {{token}}
Content-Type: application/json


{
    "name": "Fan",
    "iconName": "fan",
    "brandName": "Walton"
}


###

PATCH http://localhost:3001/api/products/addBrands/6966e0449210dfea3a8b9358
x-auth-token: {{token}}
Content-Type: application/json


{
    "brandName": "Oppo"
}

###

PATCH http://localhost:3001/api/products/addModels/6966e0449210dfea3a8b9358/6966e0449210dfea3a8b9359
x-auth-token: {{token}}
Content-Type: application/json


{
    "modelName": "Demo"
}

###

PATCH http://localhost:3001/api/products/addModelsArray/6966e0449210dfea3a8b9358/6966e07e9210dfea3a8b935d
x-auth-token: {{token}}
Content-Type: application/json


{
    "modelName": ["Demo1", "Demo2"]
}

###

GET http://localhost:3001/api/products
x-auth-token: {{token}}

###

GET http://localhost:3001/api/products/brands/6966e0449210dfea3a8b9358
x-auth-token: {{token}}

###

GET http://localhost:3001/api/products/models/6966e0449210dfea3a8b9358/6966e07e9210dfea3a8b935d
x-auth-token: {{token}}
