//Every time I have to refresh these tokens because they will be exparied after a period of time. To get new one I need to go to auth.rest and generate new tokens.
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2OTY2YzBiNGVkOGU1ZmM0N2E3MTNjZTciLCJpc0FkbWluIjp0cnVlLCJpYXQiOjE3NjgzNDgwNDksImV4cCI6MTc2ODM1MTY0OX0.hq8lwStrKpGfRsya6c8gPtr5soZ3DcwwMM1WjIfOOmU

###

GET http://localhost:3001/api/technicians?pageNumber=1&pageSize=10
x-auth-token: {{token}}

###

GET http://localhost:3001/api/technicians/allTechnicians
x-auth-token: {{token}}

###

GET http://localhost:3001/api/technicians/6966dbe548b2cc1ca29625c9
x-auth-token: {{token}}

###

POST http://localhost:3001/api/technicians
x-auth-token: {{token}}
Content-Type: application/json


{
    "name": "Jakson",
    "email": "jakson@gmail.com",
    "phone": "01956140445",
    "whatsappNumber": "01956140445",
    "region": "Dhaka",
    "city": "Munshiganj",
    "area": "Hatkhola",
    "location": "Road 2/3",
    "agentId": "6966d4f14add0fe0fdfa1a9d"
}

###

PUT http://localhost:3001/api/technicians/6966dbe548b2cc1ca29625c9
x-auth-token: {{token}}
Content-Type: application/json


{
    "name": "Jakson2",
    "email": "jakson2@gmail.com",
    "phone": "01956140423",
    "whatsappNumber": "01956140423",
    "region": "Dhaka",
    "city": "Munshiganj",
    "area": "Hatkhola",
    "location": "Road 2/3",
    "agentId": "6966d4f14add0fe0fdfa1a9d"
}

###

DELETE http://localhost:3001/api/technicians/6966dbe548b2cc1ca29625c9
x-auth-token: {{token}}
Content-Type: application/json